import './globals.css';
import '@uploadthing/react/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryClientProvider from './_providers/QueryClientProvider';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from './api/uploadthing/core';
import { AuthProvider } from './_providers/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <QueryClientProvider>
            <Header />
            <main className="flex min-h-[calc(100dvh-56px)] flex-col items-center">
              {children}
            </main>
            <Footer />
            {modal}
            <div id="modal-root" />
          </QueryClientProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
