import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import QueryClientProvider from './providers/QueryClientProvider';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryClientProvider>
            <Header />
            <main className="min-h-[calc(100dvh-56px)]">{children}</main>
            <Footer />
          </QueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
